# -*- coding: utf-8 -*-
"""RevCienBase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPHfSXobdAx2g8fYwUk1fWYIbZVPifNf
"""

!pip install langchain_community[all]

# 1. Limpia cualquier instalación corrupta previa
!pip uninstall -y langchain langchain-core langchain-community

# 2. Instala la versión base y la librería de herramientas/comunidad actualizadas
!pip install -qU langchain langchain-community langchain-core

import langchain_community as lc

!pip install -qU langchain-community xmltodict

"""## Revisor Científico con LangChain

Para construir un revisor científico, el primer paso es integrar herramientas que nos permitan consultar bases de datos científicas. Utilizaremos las herramientas de LangChain para ArXiv y PubMed.
"""

!pip install -qU arxiv

import arxiv
from langchain_community.utilities import ArxivAPIWrapper
from langchain_community.tools.arxiv import ArxivQueryRun
from langchain_community.tools.pubmed.tool import PubmedQueryRun
from typing import Any, List
from pydantic import Field

# Definir una clase FixedArxivAPIWrapper personalizada para corregir el bug en langchain_community 0.4.2
class FixedArxivAPIWrapper(ArxivAPIWrapper):
    arxiv_client: Any = Field(default_factory=arxiv.Client)
    top_k_results: int = Field(default=2) # Ajustar a 2 resultados por defecto, igual que en el ejemplo

    def _fetch_results(self, query: str) -> List[arxiv.Result]:
        search_object = arxiv.Search(
            query=query[: self.ARXIV_MAX_QUERY_LENGTH],
            max_results=self.top_k_results
        )
        results = list(self.arxiv_client.results(search_object))
        return results

    # Sobrescribir el método run para manejar la obtención y el formateo de los resultados
    def run(self, query: str) -> str:
        try:
            results = self._fetch_results(query)
        except Exception as ex:
            return f"Excepción de Arxiv: {ex}"

        if not results:
            return "No se encontraron resultados."

        docs = []
        for result in results:
            published_date = result.published.strftime('%Y-%m-%d') if result.published else 'Fecha no disponible'
            doc_str = (
                f"Publicado: {published_date}\n"
                f"Título: {result.title}\n"
                f"Autores: {', '.join(a.name for a in result.authors)}\n"
                f"Resumen: {result.summary}"
            )
            docs.append(doc_str)
        return "\n\n".join(docs)

# Define una clase FixedArxivQueryRun que utiliza el FixedArxivAPIWrapper
class FixedArxivQueryRun(ArxivQueryRun):
    # Anular el campo api_wrapper para usar nuestra clase FixedArxivAPIWrapper por defecto
    api_wrapper: FixedArxivAPIWrapper = Field(default_factory=FixedArxivAPIWrapper)

# Inicializar las herramientas usando la clase FixedArxivQueryRun para Arxiv
arxiv_tool = FixedArxivQueryRun()
pubmed_tool = PubmedQueryRun()

import pkg_resources
import os
import inspect
from pathlib import Path

# Verificar la versión de langchain-community
try:
    version = pkg_resources.get_distribution('langchain-community').version
    print(f"Versión de langchain-community instalada: {version}")
except pkg_resources.DistributionNotFound:
    print("langchain-community no está instalada o no se encontró su versión.")

try:
    import langchain_community.tools.pubmed as pubmed_module

    # List all attributes and members of the pubmed_module
    print(f"\nMiembros del módulo langchain_community.tools.pubmed:")
    for name in dir(pubmed_module):
        obj = getattr(pubmed_module, name)
        if inspect.isclass(obj) and (name.endswith('QueryRun') or name.endswith('Tool')):
            print(f"  - Clase encontrada: {name} en {obj.__module__}")
        elif not name.startswith('_'):
            print(f"  - Miembro: {name}")

    # If the class is not directly in the module, it might be in a submodule like 'tool'
    # Try importing from .tool if it exists
    try:
        import langchain_community.tools.pubmed.tool as pubmed_tool_submodule
        print(f"\nMiembros del submódulo langchain_community.tools.pubmed.tool:")
        for name in dir(pubmed_tool_submodule):
            obj = getattr(pubmed_tool_submodule, name)
            if inspect.isclass(obj) and (name.endswith('QueryRun') or name.endswith('Tool')):
                print(f"  - Clase encontrada: {name} en {obj.__module__}")
            elif not name.startswith('_'):
                print(f"  - Miembro: {name}")
    except ImportError:
        print("El submódulo 'langchain_community.tools.pubmed.tool' no existe.")

except Exception as e:
    print(f"Error al inspeccionar el módulo pubmed: {e}")

"""Ahora podemos usar estas herramientas para buscar artículos. Aquí hay un ejemplo de cómo buscar artículos relacionados con 'machine learning in prime editing' en ArXiv y 'CRISPR/Cas9 for cancer therapy' en PubMed."""

# 1. Limpiamos cualquier versión previa obsoleta o incompleta
!pip uninstall -y langchain langchain-core langchain-community

# 2. Instalamos el core, la comunidad y las dependencias para arXiv y PubMed
!pip install -qU langchain \
                langchain-core \
                langchain-community \
                arxiv \
                xmltodict

# Ejemplo de uso de la herramienta ArXiv
print("---- Búsqueda en ArXiv ----")
arxiv_result = arxiv_tool.run("machine learning in prime editing") # Se pasa la consulta como un solo argumento de cadena
print(arxiv_result)

# Ejemplo de uso de la herramienta PubMed
print("\n---- Búsqueda en PubMed ----")
pubmed_result = pubmed_tool.run("CRISPR/Cas9 for cancer therapy") # Se pasa la consulta como un solo argumento de cadena
print(pubmed_result)